import { notFound } from "next/navigation";
import type { Metadata } from "next";
import PlanOrderForm from "../pricing/PlanOrderForm";
import PlanFAQ, { type FaqItem } from "../pricing/PlanFAQ";

interface PlanPageData {
  title: string;
    description: string;
      keywords: string;
        canonical: string;
          badge: string;
            heading: string;
              price: string;
                faqItems: FaqItem[];
                }

                const planData: Record<string, PlanPageData> = {
                  "1-month": {
                      title: "1 Month IPTV Plan — $15 | MapleStreamTV Canada",
                          description: "Get 1 month of IPTV in Canada for $15. 25,000+ live channels, 4K quality, NHL, TSN, CTV and more. No contract. Login credentials sent within 5 minutes.",
                              keywords: "IPTV Canada 1 month, IPTV monthly plan Canada, IPTV $15 Canada, month to month IPTV Canada",
                                  canonical: "https://www.maplestreamtv.ca/1-month",
                                      badge: "IPTV CANADA · 1 MONTH PLAN",
                                          heading: "1 Month Plan — $15",
                                              price: "15",
                                                  faqItems: [
                                                        { q: "What is included in the 1-month IPTV plan?", a: "The 1-month plan gives you full access to 25,000+ live TV channels, 120,000+ movies & series in 4K, including NHL, TSN, Sportsnet, CTV, and more — all for $15." },
                                                              { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within 5 minutes." },
                                                                    { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                          { q: "Is there a contract or commitment required?", a: "No contracts at all. The 1-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                { q: "Can I upgrade to a longer plan later?", a: "Yes! You can upgrade to our 3-month, 6-month, or 12-month plan at any time to save more per month." },
                                                                                      { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                            { q: "Is there a free trial available?", a: "Yes, we offer a 24-hour free trial. Visit our Free Trial page to get started before committing." },
                                                                                                  { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Canadian support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                      ],
                                                                                                        },
                                                                                                          "3-months": {
                                                                                                              title: "3 Month IPTV Plan — $29 | MapleStreamTV Canada",
                                                                                                                  description: "Get 3 months of IPTV in Canada for $29. 25,000+ live channels, 4K quality, NHL, TSN, CTV and more. No contract. Login credentials sent within 5 minutes.",
                                                                                                                      keywords: "IPTV Canada 3 months, IPTV quarterly plan Canada, IPTV $29 Canada, 3 month IPTV Canada",
                                                                                                                          canonical: "https://www.maplestreamtv.ca/3-months",
                                                                                                                              badge: "IPTV CANADA · 3 MONTH PLAN",
                                                                                                                                  heading: "3 Month Plan — $29",
                                                                                                                                      price: "29",
                                                                                                                                          faqItems: [
                                                                                                                                                { q: "What is included in the 3-month IPTV plan?", a: "The 3-month plan gives you full access to 25,000+ live TV channels, 120,000+ movies & series in 4K, including NHL, TSN, Sportsnet, CTV, and more — all for $29." },
                                                                                                                                                      { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within 5 minutes." },
                                                                                                                                                            { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                                                                                                                  { q: "Is there a contract or commitment required?", a: "No contracts at all. The 3-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                                                                                                        { q: "How much do I save compared to the 1-month plan?", a: "With the 3-month plan at $29, you pay under $10/month instead of $15 — saving you over 33%." },
                                                                                                                                                                              { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                                                                                                                    { q: "Is there a free trial available?", a: "Yes, we offer a 24-hour free trial. Visit our Free Trial page to get started before committing." },
                                                                                                                                                                                          { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Canadian support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                                                                                                              ],
                                                                                                                                                                                                },
                                                                                                                                                                                                  "6-months": {
                                                                                                                                                                                                      title: "6 Month IPTV Plan — $39 | MapleStreamTV Canada",
                                                                                                                                                                                                          description: "Get 6 months of IPTV in Canada for $39. 25,000+ live channels, 4K quality, NHL, TSN, CTV and more. No contract. Login credentials sent within 5 minutes.",
                                                                                                                                                                                                              keywords: "IPTV Canada 6 months, IPTV semi-annual plan Canada, IPTV $39 Canada, 6 month IPTV Canada",
                                                                                                                                                                                                                  canonical: "https://www.maplestreamtv.ca/6-months",
                                                                                                                                                                                                                      badge: "IPTV CANADA · 6 MONTH PLAN",
                                                                                                                                                                                                                          heading: "6 Month Plan — $39",
                                                                                                                                                                                                                              price: "39",
                                                                                                                                                                                                                                  faqItems: [
                                                                                                                                                                                                                                        { q: "What is included in the 6-month IPTV plan?", a: "The 6-month plan gives you full access to 25,000+ live TV channels, 120,000+ movies & series in 4K, including NHL, TSN, Sportsnet, CTV, and more — all for $39." },
                                                                                                                                                                                                                                              { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within 5 minutes." },
                                                                                                                                                                                                                                                    { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                                                                                                                                                                                                          { q: "Is there a contract or commitment required?", a: "No contracts at all. The 6-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                                                                                                                                                                                                { q: "How much do I save compared to the 1-month plan?", a: "With the 6-month plan at $39, you pay only $6.50/month — saving you over 56% compared to the monthly plan." },
                                                                                                                                                                                                                                                                      { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                                                                                                                                                                                                            { q: "Is there a free trial available?", a: "Yes, we offer a 24-hour free trial. Visit our Free Trial page to get started before committing." },
                                                                                                                                                                                                                                                                                  { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Canadian support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                          "12-months": {
                                                                                                                                                                                                                                                                                              title: "12 Month IPTV Plan — $49 | MapleStreamTV Canada",
                                                                                                                                                                                                                                                                                                  description: "Get 12 months of IPTV in Canada for $49. 25,000+ live channels, 4K quality, NHL, TSN, CTV and more. No contract. Login credentials sent within 5 minutes.",
                                                                                                                                                                                                                                                                                                      keywords: "IPTV Canada 12 months, IPTV annual plan Canada, IPTV $49 Canada, yearly IPTV Canada",
                                                                                                                                                                                                                                                                                                          canonical: "https://www.maplestreamtv.ca/12-months",
                                                                                                                                                                                                                                                                                                              badge: "IPTV CANADA · 12 MONTH PLAN",
                                                                                                                                                                                                                                                                                                                  heading: "12 Month Plan — $49",
                                                                                                                                                                                                                                                                                                                      price: "49",
                                                                                                                                                                                                                                                                                                                          faqItems: [
                                                                                                                                                                                                                                                                                                                                { q: "What is included in the 12-month IPTV plan?", a: "The 12-month plan gives you full access to 25,000+ live TV channels, 120,000+ movies & series in 4K, including NHL, TSN, Sportsnet, CTV, and more — all for $49." },
                                                                                                                                                                                                                                                                                                                                      { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within 5 minutes." },
                                                                                                                                                                                                                                                                                                                                            { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                                                                                                                                                                                                                                                                                                  { q: "Is there a contract or commitment required?", a: "No contracts at all. The 12-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                                                                                                                                                                                                                                                                                        { q: "How much do I save compared to the 1-month plan?", a: "With the 12-month plan at $49, you pay only $4/month — saving you over 73% compared to the monthly plan." },
                                                                                                                                                                                                                                                                                                                                                              { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                                                                                                                                                                                                                                                                                                    { q: "Is there a free trial available?", a: "Yes, we offer a 24-hour free trial. Visit our Free Trial page to get started before committing." },
                                                                                                                                                                                                                                                                                                                                                                          { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Canadian support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                export async function generateMetadata({ params }: { params: Promise<{ plan: string }> }): Promise<Metadata> {
                                                                                                                                                                                                                                                                                                                                                                                  const { plan } = await params;
                                                                                                                                                                                                                                                                                                                                                                                    const data = planData[plan];
                                                                                                                                                                                                                                                                                                                                                                                      if (!data) return { title: "Plan Not Found" };
                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                            title: data.title,
                                                                                                                                                                                                                                                                                                                                                                                                description: data.description,
                                                                                                                                                                                                                                                                                                                                                                                                    keywords: data.keywords,
                                                                                                                                                                                                                                                                                                                                                                                                        alternates: { canonical: data.canonical },
                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                          export default async function PlanPage({ params }: { params: Promise<{ plan: string }> }) {
                                                                                                                                                                                                                                                                                                                                                                                                            const { plan } = await params;
                                                                                                                                                                                                                                                                                                                                                                                                              const data = planData[plan];
                                                                                                                                                                                                                                                                                                                                                                                                                if (!data) notFound();

                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <main style={{ background: "#10131E", color: "#fff", minHeight: "100vh", fontFamily: "inherit" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ maxWidth: 780, margin: "0 auto", padding: "48px 20px 80px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Badge */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginBottom: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ background: "#fd0322", color: "#fff", fontSize: 12, fontWeight: 700, padding: "5px 14px", borderRadius: 999, letterSpacing: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {data.badge}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Heading */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 style={{ fontSize: "clamp(2rem,5vw,2.8rem)", fontWeight: 900, marginBottom: 8, lineHeight: 1.15 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {data.heading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ width: 48, height: 4, background: "#fd0322", borderRadius: 2, marginBottom: 24 }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Subtitle */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ color: "#aaa", fontSize: 15, marginBottom: 36 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Fill out the form below to place your order.<br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              We&apos;ll send your login credentials to your email within 5 minutes.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Order Form */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <PlanOrderForm plan={plan} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* FAQ */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <PlanFAQ items={data.faqItems} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }